harbor:
  expose:
    type: ingress
    tls:
      certSource: secret
      secret:
        secretName: "core-harbor-tls-secret"
        notarySecretName: "notary-harbor-tls-secret"
    ingress:
      hosts:
        core: core.harbor.home.phyyou.com
        notary: notary.harbor.home.phyyou.com
      annotations:
        ingress.kubernetes.io/ssl-redirect: "true"
        ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        cert-manager.io/cluster-issuer: letsencrypt-staging
      notary:
        # notary ingress-specific annotations
        annotations: {}
        # notary ingress-specific labels
        labels: {}
      harbor:
        # harbor ingress-specific annotations
        annotations: {}
        # harbor ingress-specific labels
        labels: {}
  externalURL: https://core.harbor.home.phyyou.com
