apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eggjam-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: eggjam
  project: default
  source:
    path: charts/eggjam/backend
    repoURL: https://github.com/phyyou/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
