airflow:
  data:
    metadataConnection.host: airflow-db.airflow.svc.cluster.local

  postgresql.enabled: false

  statsd:
    enabled: false

  ingress:
    web:
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      enabled: true
      hosts:
        - airflow.phyyou.com
      ingressClassName: "nginx"
      pathType: Prefix
