airflow:
  postgresql:
    enabled: false
  data:
    metadataSecretName: airflow-db
    resultBackendSecretName: airflow-result-db
  statsd:
    enabled: false
  ingress:
    web:
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      enabled: true
      hosts:
        - airflow.phyyou.com
      ingressClassName: ""
      pathType: Prefix
  dags:
    gitSync:
      enabled: true
      branch: main
      repo: https://github.com/phyyou/SchoolFit-Airflow.git
      rev: HEAD
      depth: 1
      subPath: dags