apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anoveli-data-pipeline
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: anoveli
  project: default
  source:
    path: charts/ANovelI/data-pipeline
    repoURL: https://github.com/phyyou/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
